### ISSUE TITLE
Cisco Jabber.pkg and .download error on File Root Path/Network Share

### ISSUE THREAD

**Issue by rx7raven** [autopkg/MLBZ521-recipes#57]
Running either recipe results in a "Can't find root path or network share not mounted error".

**Comment by MLBZ521** [comment]
@rx7raven Strange.  It worked for me after testing the changes I made to the underlying recipes, but maybe it's because of an option I'm not using.  How is your "Offline Repository" setup?

I've been out of the office for the last couple weeks and won't really be back until Monday, but I'll take a look at this as soon as I get the chance.

**Comment by rx7raven** [comment]
I didn't update that offline repository path.  This can be closed.

**Comment by MLBZ521** [comment]
@rx7raven Sorry, I've been making a lot of changes to the OfflineFiles processor lately.  Trying to make it more reliable and usable in different environments.
